include("rune_rooms_scripts.pickups.anti_runes.gebo_api.main")
include("rune_rooms_scripts.pickups.anti_runes.fehu")
include("rune_rooms_scripts.pickups.anti_runes.gebo")
include("rune_rooms_scripts.pickups.anti_runes.ingwaz")
include("rune_rooms_scripts.pickups.anti_runes.kenaz")
include("rune_rooms_scripts.pickups.anti_runes.othala")
include("rune_rooms_scripts.pickups.anti_runes.sowilo")